version: '3'
services:
  midpoint:
    image: evolveum/midpoint
    container_name: midpoint
    domainname: docker
    links:
      - connid-connector-server:connid-connector-server
      - openldap:openldap
    volumes:
      - ${PWD}/midpoint-username.csv:/csv/midpoint-username.csv
      - ${PWD}/connectors:/var/opt/midpoint/icf-connectors/
      - ${PWD}/schema:/var/opt/midpoint/schema/
      - ${PWD}/data:/data
  connid-connector-server:
    image: mans0954/connid-connector-server
    container_name: connid-connector-server
    domainname: docker
  openldap:
    image: osixia/openldap
    container_name: openldap
    domainname: docker
    environment:
      LDAP_TLS: 'true'
      LDAP_TLS_CRT_FILENAME: 'fullchain.pem'
      LDAP_TLS_KEY_FILENAME: 'privkey.pem'
      LDAP_TLS_CA_CRT_FILENAME: 'fullchain.pem'
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: "dc=example,dc=org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_TLS_VERIFY_CLIENT: "allow"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "639:639"
    hostname: "openldap.docker"


